# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{javagems}
  s.version = "0.4.11"

  s.required_rubygems_version = Gem::Requirement.new(">= 1.3.5") if s.respond_to? :required_rubygems_version=
  s.authors = ["gabrielg", "jaknowlden"]
  s.date = %q{2009-11-24}
  s.description = %q{Provides gem-esque support to Java}
  s.email = %q{gabriel.gironda@gmail.com}
  s.executables = ["jam", "jamc", "javagem", "javagem-exec"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "bin/jam",
     "bin/jamc",
     "bin/javagem",
     "bin/javagem-exec",
     "javagems.gemspec",
     "lib/javagems.rb",
     "lib/javagems/classpath_builder.rb",
     "lib/javagems/gem_overrides.rb",
     "lib/javagems/jam.rb",
     "lib/rubygems/commands/classpath_command.rb",
     "test/classpath_command_test.rb",
     "test/gem_overrides_test.rb",
     "test/invalid_test_app/Gemfile",
     "test/invalid_test_app/vendor/gems/dirs/test-gem-four/.document",
     "test/invalid_test_app/vendor/gems/dirs/test-gem-four/.gitignore",
     "test/invalid_test_app/vendor/gems/dirs/test-gem-four/LICENSE",
     "test/invalid_test_app/vendor/gems/dirs/test-gem-four/README.rdoc",
     "test/invalid_test_app/vendor/gems/dirs/test-gem-four/Rakefile",
     "test/invalid_test_app/vendor/gems/dirs/test-gem-four/VERSION",
     "test/invalid_test_app/vendor/gems/dirs/test-gem-four/lib/test-gem-four.rb",
     "test/invalid_test_app/vendor/gems/dirs/test-gem-four/test-gem-four.gemspec",
     "test/invalid_test_app/vendor/gems/dirs/test-gem-four/test/helper.rb",
     "test/invalid_test_app/vendor/gems/dirs/test-gem-four/test/test_test-gem-four.rb",
     "test/invalid_test_app/vendor/gems/dirs/test-gem-one/.document",
     "test/invalid_test_app/vendor/gems/dirs/test-gem-one/.gitignore",
     "test/invalid_test_app/vendor/gems/dirs/test-gem-one/LICENSE",
     "test/invalid_test_app/vendor/gems/dirs/test-gem-one/README.rdoc",
     "test/invalid_test_app/vendor/gems/dirs/test-gem-one/Rakefile",
     "test/invalid_test_app/vendor/gems/dirs/test-gem-one/VERSION",
     "test/invalid_test_app/vendor/gems/dirs/test-gem-one/lib/test-gem-one.rb",
     "test/invalid_test_app/vendor/gems/dirs/test-gem-one/test-gem-one.gemspec",
     "test/invalid_test_app/vendor/gems/dirs/test-gem-one/test/helper.rb",
     "test/invalid_test_app/vendor/gems/dirs/test-gem-one/test/test_test-gem-one.rb",
     "test/invalid_test_app/vendor/gems/dirs/test-gem-two/.document",
     "test/invalid_test_app/vendor/gems/dirs/test-gem-two/.gitignore",
     "test/invalid_test_app/vendor/gems/dirs/test-gem-two/LICENSE",
     "test/invalid_test_app/vendor/gems/dirs/test-gem-two/README.rdoc",
     "test/invalid_test_app/vendor/gems/dirs/test-gem-two/Rakefile",
     "test/invalid_test_app/vendor/gems/dirs/test-gem-two/VERSION",
     "test/invalid_test_app/vendor/gems/dirs/test-gem-two/lib/test-gem-two.rb",
     "test/invalid_test_app/vendor/gems/dirs/test-gem-two/test-gem-two.gemspec",
     "test/invalid_test_app/vendor/gems/dirs/test-gem-two/test/helper.rb",
     "test/invalid_test_app/vendor/gems/dirs/test-gem-two/test/test_test-gem-two.rb",
     "test/invalid_test_app/vendor/gems/environment.rb",
     "test/invalid_test_app/vendor/gems/specifications/test-gem-four-0.0.0.gemspec",
     "test/invalid_test_app/vendor/gems/specifications/test-gem-one-0.0.0.gemspec",
     "test/invalid_test_app/vendor/gems/specifications/test-gem-two-0.0.0.gemspec",
     "test/jam_test.rb",
     "test/test_helper.rb",
     "test/valid_test_app/Gemfile",
     "test/valid_test_app/vendor/gems/dirs/test-gem-four/.document",
     "test/valid_test_app/vendor/gems/dirs/test-gem-four/.gitignore",
     "test/valid_test_app/vendor/gems/dirs/test-gem-four/LICENSE",
     "test/valid_test_app/vendor/gems/dirs/test-gem-four/README.rdoc",
     "test/valid_test_app/vendor/gems/dirs/test-gem-four/Rakefile",
     "test/valid_test_app/vendor/gems/dirs/test-gem-four/VERSION",
     "test/valid_test_app/vendor/gems/dirs/test-gem-four/lib/test-gem-four.rb",
     "test/valid_test_app/vendor/gems/dirs/test-gem-four/test-gem-four.gemspec",
     "test/valid_test_app/vendor/gems/dirs/test-gem-four/test/helper.rb",
     "test/valid_test_app/vendor/gems/dirs/test-gem-four/test/test_test-gem-four.rb",
     "test/valid_test_app/vendor/gems/dirs/test-gem-one/.document",
     "test/valid_test_app/vendor/gems/dirs/test-gem-one/.gitignore",
     "test/valid_test_app/vendor/gems/dirs/test-gem-one/LICENSE",
     "test/valid_test_app/vendor/gems/dirs/test-gem-one/README.rdoc",
     "test/valid_test_app/vendor/gems/dirs/test-gem-one/Rakefile",
     "test/valid_test_app/vendor/gems/dirs/test-gem-one/VERSION",
     "test/valid_test_app/vendor/gems/dirs/test-gem-one/lib/test-gem-one.rb",
     "test/valid_test_app/vendor/gems/dirs/test-gem-one/test-gem-one.gemspec",
     "test/valid_test_app/vendor/gems/dirs/test-gem-one/test/helper.rb",
     "test/valid_test_app/vendor/gems/dirs/test-gem-one/test/test_test-gem-one.rb",
     "test/valid_test_app/vendor/gems/dirs/test-gem-three/.document",
     "test/valid_test_app/vendor/gems/dirs/test-gem-three/.gitignore",
     "test/valid_test_app/vendor/gems/dirs/test-gem-three/LICENSE",
     "test/valid_test_app/vendor/gems/dirs/test-gem-three/README.rdoc",
     "test/valid_test_app/vendor/gems/dirs/test-gem-three/Rakefile",
     "test/valid_test_app/vendor/gems/dirs/test-gem-three/VERSION",
     "test/valid_test_app/vendor/gems/dirs/test-gem-three/lib/test-gem-three.rb",
     "test/valid_test_app/vendor/gems/dirs/test-gem-three/test-gem-three.gemspec",
     "test/valid_test_app/vendor/gems/dirs/test-gem-three/test/helper.rb",
     "test/valid_test_app/vendor/gems/dirs/test-gem-three/test/test_test-gem-three.rb",
     "test/valid_test_app/vendor/gems/dirs/test-gem-two/.document",
     "test/valid_test_app/vendor/gems/dirs/test-gem-two/.gitignore",
     "test/valid_test_app/vendor/gems/dirs/test-gem-two/LICENSE",
     "test/valid_test_app/vendor/gems/dirs/test-gem-two/README.rdoc",
     "test/valid_test_app/vendor/gems/dirs/test-gem-two/Rakefile",
     "test/valid_test_app/vendor/gems/dirs/test-gem-two/VERSION",
     "test/valid_test_app/vendor/gems/dirs/test-gem-two/lib/test-gem-two.rb",
     "test/valid_test_app/vendor/gems/dirs/test-gem-two/test-gem-two.gemspec",
     "test/valid_test_app/vendor/gems/dirs/test-gem-two/test/helper.rb",
     "test/valid_test_app/vendor/gems/dirs/test-gem-two/test/test_test-gem-two.rb",
     "test/valid_test_app/vendor/gems/environment.rb",
     "test/valid_test_app/vendor/gems/specifications/test-gem-four-0.0.0.gemspec",
     "test/valid_test_app/vendor/gems/specifications/test-gem-one-0.0.0.gemspec",
     "test/valid_test_app/vendor/gems/specifications/test-gem-three-0.0.0.gemspec",
     "test/valid_test_app/vendor/gems/specifications/test-gem-two-0.0.0.gemspec"
  ]
  s.homepage = %q{http://www.javagems.org/}
  s.post_install_message = %q{Choosy clojurers choose Thumblemonks

Remember to add ~/.javagem/java/bin to your PATH environment
variable for maximum-JavaGems-fun-times.
}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{A gem for the javagems system}
  s.test_files = [
    "test/classpath_command_test.rb",
     "test/gem_overrides_test.rb",
     "test/invalid_test_app/vendor/gems/dirs/test-gem-four/lib/test-gem-four.rb",
     "test/invalid_test_app/vendor/gems/dirs/test-gem-four/test/helper.rb",
     "test/invalid_test_app/vendor/gems/dirs/test-gem-four/test/test_test-gem-four.rb",
     "test/invalid_test_app/vendor/gems/dirs/test-gem-one/lib/test-gem-one.rb",
     "test/invalid_test_app/vendor/gems/dirs/test-gem-one/test/helper.rb",
     "test/invalid_test_app/vendor/gems/dirs/test-gem-one/test/test_test-gem-one.rb",
     "test/invalid_test_app/vendor/gems/dirs/test-gem-two/lib/test-gem-two.rb",
     "test/invalid_test_app/vendor/gems/dirs/test-gem-two/test/helper.rb",
     "test/invalid_test_app/vendor/gems/dirs/test-gem-two/test/test_test-gem-two.rb",
     "test/invalid_test_app/vendor/gems/environment.rb",
     "test/jam_test.rb",
     "test/test_helper.rb",
     "test/valid_test_app/vendor/gems/dirs/test-gem-four/lib/test-gem-four.rb",
     "test/valid_test_app/vendor/gems/dirs/test-gem-four/test/helper.rb",
     "test/valid_test_app/vendor/gems/dirs/test-gem-four/test/test_test-gem-four.rb",
     "test/valid_test_app/vendor/gems/dirs/test-gem-one/lib/test-gem-one.rb",
     "test/valid_test_app/vendor/gems/dirs/test-gem-one/test/helper.rb",
     "test/valid_test_app/vendor/gems/dirs/test-gem-one/test/test_test-gem-one.rb",
     "test/valid_test_app/vendor/gems/dirs/test-gem-three/lib/test-gem-three.rb",
     "test/valid_test_app/vendor/gems/dirs/test-gem-three/test/helper.rb",
     "test/valid_test_app/vendor/gems/dirs/test-gem-three/test/test_test-gem-three.rb",
     "test/valid_test_app/vendor/gems/dirs/test-gem-two/lib/test-gem-two.rb",
     "test/valid_test_app/vendor/gems/dirs/test-gem-two/test/helper.rb",
     "test/valid_test_app/vendor/gems/dirs/test-gem-two/test/test_test-gem-two.rb",
     "test/valid_test_app/vendor/gems/environment.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<gemcutter>, [">= 0"])
      s.add_runtime_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<riot>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
    else
      s.add_dependency(%q<gemcutter>, [">= 0"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<riot>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
    end
  else
    s.add_dependency(%q<gemcutter>, [">= 0"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<riot>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
  end
end

